# Generated by Django 2.2.2 on 2020-05-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0003_auto_20200516_2322'),
        ('management', '0004_auto_20200517_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='main_subject',
        ),
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.ManyToManyField(null=True, to='results.Subject'),
        ),
    ]
