# Generated by Django 2.2.2 on 2020-05-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200517_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.ManyToManyField(to='results.Subject'),
        ),
    ]
