# Generated by Django 2.2.2 on 2020-05-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20200517_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_employed',
            field=models.DateField(null=True),
        ),
    ]
