# Generated by Django 2.2.2 on 2020-05-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20200517_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
