# Generated by Django 2.2.2 on 2020-05-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_user_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classes',
            field=models.ManyToManyField(to='management.Class'),
        ),
    ]
