# Generated by Django 2.2.2 on 2020-05-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20200518_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='student_view_student_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='teacher_view_student_details',
            field=models.BooleanField(default=True),
        ),
    ]
