# Generated by Django 2.2.2 on 2020-05-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20200518_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('limit', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='student_can_send_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='teacher_can_send_student_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Plan'),
        ),
    ]
