# Generated by Django 2.2.2 on 2020-08-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20200519_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.CharField(choices=[('ABI', 'Abia'), ('ADA', 'Adamawa'), ('AKW', 'Akwa-Ibom'), ('ANA', 'Anambra'), ('BAU', 'Bauchi'), ('Bayelsa State', 'Bayelsa'), ('Benue State', 'Benue'), ('Borno State', 'Borno'), ('Cross River State', 'Cross'), ('Delta State', 'Delta'), ('Ebonyi State', 'Ebonyi'), ('Enugu State', 'Enugu'), ('Edo State', 'Edo'), ('FCT - Abuja', 'FCT - Abuja'), ('Gombe State', 'Gombe'), ('Imo State', 'Imo'), ('Kaduna State', 'Kaduna'), ('Kano State', 'Kano'), ('Katsina State', 'Katsina'), ('Kebbi State', 'Kebbi'), ('Kogi State', 'Kogi'), ('Kwara State', 'Kwara'), ('Lagos State', 'Lagos'), ('Nasarawa State', 'Nasarawa'), ('Niger State', 'Niger'), ('Ogun State', 'Ogun'), ('Ondo State', 'Ondo'), ('Oyo State', 'Oyo'), ('Plateau State', 'Plateau'), ('Rivers State', 'Rivers'), ('Sokoto State', 'Sokoto'), ('Taraba State', 'Taraba'), ('Yobe State', 'Yobe'), ('Zamfara State', 'Zamfara')], default='ABI', max_length=100),
        ),
    ]
