# Generated by Django 2.2.2 on 2020-08-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_user_date_admitted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_admitted',
            new_name='admission_date',
        ),
    ]
